language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  - SYMFONY_VERSION=2.8.*

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=3.1.*
    - php: 7.0
      env: SYMFONY_VERSION=3.2.*
  allow_failures:
    - php: hhvm

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - phpenv config-rm xdebug.ini
  - php composer.phar require symfony/symfony:${SYMFONY_VERSION} --no-update
  - php composer.phar update --prefer-stable --prefer-lowest

notifications:
  email:
    - bartlomiej.ojrzenski@pixers.pl
